# Tugas 4

### **Klasifikasi dataset iris menggunakan metode Naive Bayes**

Naive Bayes adalah metode yang cocok untuk klasifikasi biner dan multiclass. Metode yang juga dikenal sebagai Naive Bayes Classifier ini menerapkan teknik supervised klasifikasi objek di masa depan dengan menetapkan label kelas ke instance/catatan menggunakan probabilitas bersyarat.

Probabilitas bersyarat adalah ukuran peluang suatu peristiwa yang terjadi berdasarkan peristiwa lain yang telah (dengan asumsi, praduga, pernyataan, atau terbukti) terjadi.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
#source data
dataset_url = "https://raw.githubusercontent.com/AchmadFanyFadheli200411100088/datamining-/main/Iris.csv"
#create dataframe
df = pd.read_csv(dataset_url)

In [ ]:
#menetapkan 4 variabel independen ke X dan variabel dependen 'spesies' ke Y
X = df.iloc[:,:4].values
y = df['Species'].values

In [ ]:
#looking at the first 5 values of the dataset
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Memisahkan dataset menjadi Training set dan Test set

Setelah mendapatkan sebuah dataset, lalu dataset tersebut dibagi menjadi Training set dan Test set. Dalam kumpulan data ini, ada 150 baris dengan 50 baris masing-masing dari 3 kelas. Karena setiap kelas diberikan dalam urutan yang berkelanjutan, kita perlu membagi dataset secara acak.

Di sini, kita memiliki test_size=0.2, yang berarti bahwa 20% dari dataset akan digunakan untuk tujuan pengujian sebagai **test set** dan 80% sisanya akan digunakan sebagai **training set** untuk melatih model klasifikasi Naive Bayes.

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

Penskalaan Fitur

Dataset diperkecil ke rentang yang lebih kecil menggunakan opsi Penskalaan Fitur. Dalam hal ini, nilai X_train dan X_test diperkecil ke nilai yang lebih kecil untuk meningkatkan kecepatan program.

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Melatih model Klasifikasi Naive Bayes pada Training Set

Pada langkah ini, memperkenalkan kelas **GaussianNB** yang digunakan dari library sklearn.naive_bayes, ada beberapa model lain seperti Bernoulli, Categorical dan Multinomial. Di sini, kami menetapkan kelas GaussianNB ke pengklasifikasi variabel dan memasukkan **nilai X_train** dan **y_train** ke dalamnya untuk tujuan pelatihan.

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

Memprediksi hasil Test Set

Setelah model dilatih, selanjutnya menggunakan classifier.predict() untuk memprediksi nilai untuk Test set dan nilai yang diprediksi disimpan ke variabel **y_pred**.

In [ ]:
y_pred = classifier.predict(X_test) 
y_pred

array(['Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica'], dtype='<U15')

Confusion Matrix dan Akurasi

Ini adalah langkah yang banyak digunakan dalam teknik klasifikasi. Dalam hal ini, kita melihat Akurasi model yang dilatih dan memplot confusion matrix.

**Confusion matrix** adalah tabel yang digunakan untuk menunjukkan jumlah prediksi yang benar dan salah pada masalah klasifikasi ketika nilai nyata dari Test Set diketahui.

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm

Accuracy :  1.0

array([[12,  0,  0],
       [ 0, 10,  0],
       [ 0,  0,  8]])

Dari confusion matrix di atas, dapat disimpulkan bahwa, dari 30 data test set semua diklasifikasikan dengan benar. Ini memberikan akurasi tinggi 100%.